// app/career/jobData.js
export const jobListings = [
    {
        id: 1,
        title: 'Senior Full Stack Developer',
        department: 'Engineering',
        location: 'Dhaka, Bangladesh',
        type: 'Full-time',
        salary: '80k - 120k BDT',
        postedDate: '12-10-2025',
        deadline: '12-11-2025',
        description:
            'We are looking for an experienced Full Stack Developer to join our growing team. You will be responsible for developing and maintaining both client and server software, working with modern technologies and frameworks.',
        responsibilities: [
            'Design and develop scalable web applications',
            'Write clean, maintainable code following best practices',
            'Collaborate with cross-functional teams',
            'Participate in code reviews and technical discussions',
            'Mentor junior developers and share knowledge',
            'Contribute to technical architecture decisions',
        ],
        requirements: [
            '5+ years of experience in full-stack development',
            'Strong proficiency in React and Node.js',
            'Experience with database design and optimization',
            'Familiarity with cloud platforms (AWS/Azure)',
            'Excellent problem-solving skills',
            'Strong communication and teamwork abilities',
        ],
        benefits: [
            'Competitive salary and performance bonuses',
            'Health insurance for you and your family',
            'Flexible working hours and remote work options',
            'Professional development opportunities',
            'Modern office with great amenities',
            'Annual team retreats and events',
        ],
    },
    {
        id: 2,
        title: 'Frontend Engineer (React/Next.js)',
        department: 'Engineering',
        location: 'Dhaka, Bangladesh',
        type: 'Full-time',
        salary: '60k - 90k BDT',
        postedDate: '12-10-2025',
        deadline: '12-11-2025',
        description:
            'We are seeking a Frontend Engineer with strong React and Next.js skills to develop modern web interfaces for our OTT and enterprise projects.',
        responsibilities: [
            'Develop and optimize responsive UIs with React/Next.js',
            'Integrate RESTful APIs and handle client-side state',
            'Ensure cross-browser compatibility and accessibility',
            'Collaborate with designers and backend engineers',
            'Contribute to component library and design system',
        ],
        requirements: [
            '3+ years of experience in frontend development',
            'Strong understanding of React, Next.js, and Tailwind',
            'Knowledge of version control systems (Git, Bitbucket)',
            'Experience with performance optimization techniques',
            'Good problem-solving and communication skills',
        ],
        benefits: [
            'Competitive salary and yearly bonus',
            'Friendly and collaborative team environment',
            'Opportunity to work on high-traffic OTT platforms',
            'Training sessions and tech workshops',
        ],
    },
    {
        id: 3,
        title: 'Backend Developer (Node.js)',
        department: 'Engineering',
        location: 'Dhaka, Bangladesh',
        type: 'Full-time',
        salary: '70k - 100k BDT',
        postedDate: '12-10-2025',
        deadline: '22-10-2025',
        description:
            'We are hiring a Backend Developer with solid experience in Node.js and database design to build scalable server-side solutions.',
        responsibilities: [
            'Build and maintain RESTful APIs',
            'Design database schemas and optimize queries',
            'Implement authentication and authorization systems',
            'Write reusable and testable code',
            'Collaborate with frontend and mobile teams',
        ],
        requirements: [
            '3+ years of experience with Node.js and Express.js',
            'Experience with MongoDB or MySQL',
            'Understanding of REST API design and security',
            'Knowledge of microservices architecture is a plus',
        ],
        benefits: [
            'Performance-based salary growth',
            'Remote work flexibility',
            'Medical and wellness benefits',
            'Learning and certification opportunities',
        ],
    },
    {
        id: 4,
        title: 'UI/UX Designer',
        department: 'Design',
        location: 'Dhaka, Bangladesh',
        type: 'Full-time',
        salary: '50k - 80k BDT',
        postedDate: '12-10-2025',
        deadline: '12-11-2025',
        description:
            'We are looking for a creative UI/UX Designer to create engaging user experiences and intuitive interfaces for our digital platforms.',
        responsibilities: [
            'Design intuitive interfaces for web and mobile',
            'Conduct user research and usability testing',
            'Work closely with developers to ensure design fidelity',
            'Create wireframes, mockups, and prototypes',
        ],
        requirements: [
            '2+ years of experience as a UI/UX designer',
            'Proficiency with Figma or Adobe XD',
            'Strong visual design and typography skills',
            'Understanding of responsive design principles',
        ],
        benefits: [
            'Creative and collaborative work environment',
            'Flexible working schedule',
            'Performance-based bonus',
        ],
    },
];
