// seoConfig.js
export default [
    {
        id: 1,
        slug: 'top-10-it-infrastructure-trends-to-watch-in-2025',
        title: 'Top 10 IT Infrastructure Trends to Watch in 2025',
        description: 'Stay ahead of the curve with these top 10 IT infrastructure trends shaping the enterprise landscape in 2025.',
        keywords: 'IT infrastructure, edge computing, hybrid cloud, AI monitoring, zero trust, Kubernetes, green data centers, SASE, 5G, IaC, quantum networking',
        og_title: 'Top 10 IT Infrastructure Trends to Watch in 2025',
        og_description: 'Discover the top trends in IT infrastructure for 2025, from edge computing to quantum-ready networking.',
        og_image: 'https://example.com/images/it-infrastructure-trends-2025.jpg',
        twitter_title: 'Top 10 IT Infrastructure Trends to Watch in 2025',
        twitter_description: 'Explore the defining IT infrastructure trends of 2025, from edge computing to green data centers.',
        twitter_image: 'https://example.com/images/it-infrastructure-trends-2025.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/top-10-it-infrastructure-trends-to-watch-in-2025',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'John Doe',
        publisher: 'Aetherix',
    },
    {
        id: 2,
        slug: 'ai-revolutionizing-digital-marketing',
        title: 'How AI Is Revolutionizing Digital Marketing',
        description: 'Unpack how AI-driven tools—from chatbots to predictive analytics—are transforming every aspect of digital marketing.',
        keywords: 'AI marketing, chatbots, predictive analytics, personalization, programmatic ads, digital marketing trends',
        og_title: 'How AI Is Revolutionizing Digital Marketing',
        og_description: 'Learn how AI is transforming digital campaigns through hyper-personalization, chatbots, and smarter ad buying.',
        og_image: 'https://example.com/images/ai-digital-marketing.jpg',
        twitter_title: 'How AI Is Revolutionizing Digital Marketing',
        twitter_description: 'Discover the AI tools reshaping digital marketing, from chatbots to predictive insights.',
        twitter_image: 'https://example.com/images/ai-digital-marketing.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/ai-revolutionizing-digital-marketing',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Jane Smith',
        publisher: 'Aetherix',
    },
    {
        id: 3,
        slug: 'ultimate-guide-to-seo-in-2025',
        title: 'The Ultimate Guide to SEO in 2025: Voice, Video & Beyond',
        description: 'Future-proof your organic strategy by mastering voice search, video SEO, AI-powered optimization, and more.',
        keywords: 'SEO 2025, voice search, video SEO, AI optimization, organic strategy, future SEO',
        og_title: 'The Ultimate Guide to SEO in 2025: Voice, Video & Beyond',
        og_description: 'Master the SEO trends of 2025, including voice search, video optimization, and AI-driven content.',
        og_image: 'https://example.com/images/seo-2025.jpg',
        twitter_title: 'The Ultimate Guide to SEO in 2025: Voice, Video & Beyond',
        twitter_description: 'Stay ahead with voice, video, and AI SEO tactics for 2025.',
        twitter_image: 'https://example.com/images/seo-2025.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/ultimate-guide-to-seo-in-2025',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Alex Patel',
        publisher: 'Aetherix',
    },
    {
        id: 4,
        slug: 'building-bulletproof-cybersecurity-strategy',
        title: 'Building a Bulletproof Cybersecurity Strategy',
        description: 'Learn a step-by-step approach to threat modeling, zero-trust frameworks, and incident response planning.',
        keywords: 'cybersecurity, zero trust, threat modeling, incident response, security strategy',
        og_title: 'Building a Bulletproof Cybersecurity Strategy',
        og_description: 'Step through threat modeling, zero-trust architectures, and response planning to secure your organization.',
        og_image: 'https://example.com/images/cybersecurity-strategy.jpg',
        twitter_title: 'Building a Bulletproof Cybersecurity Strategy',
        twitter_description: 'Develop a robust cybersecurity plan with zero-trust, threat modeling, and incident response.',
        twitter_image: 'https://example.com/images/cybersecurity-strategy.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/building-bulletproof-cybersecurity-strategy',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Maria Gomez',
        publisher: 'Aetherix',
    },
    {
        id: 5,
        slug: 'content-marketing-2-0-storytelling',
        title: 'Content Marketing 2.0: Storytelling in the Age of Short Attention Spans',
        description: 'Discover interactive, micro-video, and AR/VR techniques to engage audiences with compelling narratives.',
        keywords: 'content marketing, storytelling, micro video, AR, VR, engagement',
        og_title: 'Content Marketing 2.0: Storytelling in the Age of Short Attention Spans',
        og_description: 'Engage modern audiences with micro-videos, interactive articles, and immersive AR/VR storytelling.',
        og_image: 'https://example.com/images/content-marketing-2-0.jpg',
        twitter_title: 'Content Marketing 2.0: Storytelling in the Age of Short Attention Spans',
        twitter_description: 'Learn new storytelling formats—micro-videos, interactivity, AR/VR—to capture fast-moving audiences.',
        twitter_image: 'https://example.com/images/content-marketing-2-0.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/content-marketing-2-0-storytelling',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Liam Wong',
        publisher: 'Aetherix',
    },
    {
        id: 6,
        slug: 'social-media-advertising-best-practices',
        title: 'Social Media Advertising: Platforms, Budgets & Best Practices',
        description: 'Compare ad strategies across Facebook, Instagram, LinkedIn, TikTok and optimize spend for ROI.',
        keywords: 'social media ads, Facebook ads, Instagram, LinkedIn, TikTok, advertising budget',
        og_title: 'Social Media Advertising: Platforms, Budgets & Best Practices',
        og_description: 'Optimize your social ad spend with platform comparisons, creative tips, and ROI measurement.',
        og_image: 'https://example.com/images/social-media-ads.jpg',
        twitter_title: 'Social Media Advertising: Platforms, Budgets & Best Practices',
        twitter_description: 'From Facebook to TikTok, learn how to budget, craft, and measure high-impact social ads.',
        twitter_image: 'https://example.com/images/social-media-ads.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/social-media-advertising-best-practices',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Sophia Lee',
        publisher: 'Aetherix',
    },
    {
        id: 7,
        slug: 'email-marketing-that-converts',
        title: 'Email Marketing That Converts: Segmentation, Automation & GDPR',
        description: 'Master list hygiene, automated workflows, GDPR compliance, and A/B testing for higher CTRs.',
        keywords: 'email marketing, segmentation, automation, GDPR, AB testing, deliverability',
        og_title: 'Email Marketing That Converts: Segmentation, Automation & GDPR',
        og_description: 'Boost conversion with targeted segments, automated campaigns, GDPR best practices, and tests.',
        og_image: 'https://example.com/images/email-marketing.jpg',
        twitter_title: 'Email Marketing That Converts: Segmentation, Automation & GDPR',
        twitter_description: 'Learn segmentation, automation, and compliance techniques for email campaigns that convert.',
        twitter_image: 'https://example.com/images/email-marketing.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/email-marketing-that-converts',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Noah Davis',
        publisher: 'Aetherix',
    },
    {
        id: 8,
        slug: 'ppc-advertising-demystified',
        title: 'PPC Advertising Demystified: From Keyword Research to Landing-Page Optimization',
        description: 'A step-by-step PPC playbook covering keyword tools, campaign structure, and Quality Score.',
        keywords: 'PPC, Google Ads, Microsoft Ads, keyword research, landing page, Quality Score',
        og_title: 'PPC Advertising Demystified: From Keyword Research to Landing-Page Optimization',
        og_description: 'Optimize PPC campaigns end-to-end: research, structure, landing-page best practices, metrics.',
        og_image: 'https://example.com/images/ppc-demystified.jpg',
        twitter_title: 'PPC Advertising Demystified: From Keyword Research to Landing-Page Optimization',
        twitter_description: 'Learn effective PPC strategies: keyword research, campaign setup, and landing-page tips.',
        twitter_image: 'https://example.com/images/ppc-demystified.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/ppc-advertising-demystified',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Olivia Martinez',
        publisher: 'Aetherix',
    },
    {
        id: 9,
        slug: 'harnessing-data-analytics-for-marketing',
        title: 'Harnessing Data Analytics for Smarter Marketing Decisions',
        description: 'From UTMs to GA4 dashboards, learn how to turn raw data into actionable marketing insights.',
        keywords: 'data analytics, marketing insights, GA4, dashboards, UTMs, data-driven marketing',
        og_title: 'Harnessing Data Analytics for Smarter Marketing Decisions',
        og_description: 'Transform your data into insights with tracking setup, dashboards, and analysis best practices.',
        og_image: 'https://example.com/images/data-analytics-marketing.jpg',
        twitter_title: 'Harnessing Data Analytics for Smarter Marketing Decisions',
        twitter_description: 'Master GA4, UTMs, and dashboard design to make data-driven marketing decisions.',
        twitter_image: 'https://example.com/images/data-analytics-marketing.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/harnessing-data-analytics-for-marketing',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Ethan Clark',
        publisher: 'Aetherix',
    },
    {
        id: 10,
        slug: 'ux-ui-design-principles-for-marketers',
        title: 'UX/UI Design Principles Every Marketer Should Know',
        description: 'Learn the fundamentals of user flows, responsive layouts, and accessibility to boost engagement.',
        keywords: 'UX design, UI design, user flows, responsive, accessibility, marketer resources',
        og_title: 'UX/UI Design Principles Every Marketer Should Know',
        og_description: 'Discover key UX/UI concepts—flow, layout, accessibility—to improve your marketing assets.',
        og_image: 'https://example.com/images/ux-ui-design.jpg',
        twitter_title: 'UX/UI Design Principles Every Marketer Should Know',
        twitter_description: 'Apply UX/UI best practices—flow, layout, accessibility—to enhance your marketing materials.',
        twitter_image: 'https://example.com/images/ux-ui-design.jpg',
        canonical: 'https://aetherix-azure.vercel.app/blogs/ux-ui-design-principles-for-marketers',
        robots: 'index, follow',
        viewport: 'width=device-width, initial-scale=1',
        author: 'Ava Johnson',
        publisher: 'Aetherix',
    },
]
